# pylint: skip-file
# Generated by Django 3.2.16 on 2023-01-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amazonasinitem',
            options={'verbose_name': 'Amazon ASIN item'},
        ),
        migrations.AddField(
            model_name='amazonasinitem',
            name='metadata',
            field=models.TextField(default=True, max_length=16777216, null=True),
        ),
    ]
