# pylint: skip-file
# Generated by Django 3.2.16 on 2023-01-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_auto_20230111_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonasinitem',
            name='metadata',
            field=models.TextField(blank=True, max_length=16777216, null=True),
        ),
    ]
