# pylint: skip-file
# Generated by Django 3.2.20 on 2023-11-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_amazonasinitem_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonasinitem',
            name='brand',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='amazonasinitem',
            name='seller',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
